name: Portfolio CI/CD workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#jobs
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        working-directory: ./api
        run: npm install
      - name: run tests
        working-directory: ./api
        run: npm run test
  deploy:
    name: deploy
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    needs: test
    env:
      NPM_CONFIG_PREFIX: "~/.npm-global"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TW_CONSUMER_KEY: ${{ secrets.TW_CONSUMER_KEY }}
      TW_CONSUMER_SECRET: ${{ secrets.TW_CONSUMER_SECRET }}
      TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
      TW_ACCESS_TOKEN_SECRET: ${{ secrets.TW_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        working-directory: ./api
        run: npm install
      - name: Serverless install
        working-directory: ./api
        run: npm install -g serverless && serverless deploy
